(function(root){
'use strict';
const escape=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),get=(s,y)=>s?.points.find(p=>p.year===String(y)),n=v=>Number(v).toLocaleString('pt-BR',{maximumFractionDigits:2}),palette=['var(--navy)','var(--blue-2)','var(--yellow)','var(--teal)','var(--coral)','var(--purple)'];
function label(s,rows){return s.entity?s.entity+' · '+s.scope:new Set(rows.map(r=>r.s.title)).size===1?s.scope:s.title+(s.scope==='UFSCar'?'':' · '+s.scope);}
function partition(group,byid,year){const rows=group.ids.map(id=>({s:byid[id],p:get(byid[id],year)})),total=get(byid[group.total],year);if(!group.partition||!total||total.value<=0||rows.some(r=>!r.p))return null;const sum=rows.reduce((n,r)=>n+r.p.value,0);if(Math.abs(sum-total.value)>.011)return null;return {rows,total};}
function structure(group,byid,year){
 if(group.flow){const {stock,added,removed}=group.flow,initial=get(byid[stock],Number(year)-1),add=get(byid[added],year),subtract=get(byid[removed],year),closing=get(byid[stock],year);if(!initial||!add||!subtract||!closing||Math.abs(initial.value+add.value-subtract.value-closing.value)>.00001)return {title:'Movimentação de recomendações',html:'<p class="empty">Sem conciliação completa do saldo para este ano.</p>'};
 const steps=[{label:'Saldo inicial',start:0,end:initial.value,color:'var(--navy)'},{label:'Emitidas',start:initial.value,end:initial.value+add.value,color:'var(--yellow)'},{label:'Concluídas',start:initial.value+add.value,end:closing.value,color:'var(--teal)'},{label:'Saldo final',start:0,end:closing.value,color:'var(--navy)'}],max=Math.max(...steps.flatMap(s=>[s.start,s.end]))*1.2,H=255,L=26,base=210,scale=170/max;
 let svg='<svg viewBox="0 0 510 255" role="img" aria-label="Movimentação do saldo de recomendações"><title>Saldo inicial + emitidas − concluídas = saldo final</title>';
 steps.forEach((s,i)=>{const lo=Math.min(s.start,s.end),hi=Math.max(s.start,s.end),x=L+i*122;svg+=`<rect x="${x}" y="${base-hi*scale}" width="90" height="${Math.max(1,(hi-lo)*scale)}" rx="4" fill="${s.color}"/><text class="chart-label" x="${x+45}" y="${base-hi*scale-10}" text-anchor="middle">${n(i===0?initial.value:i===1?add.value:i===2?subtract.value:closing.value)}</text><text class="chart-label" x="${x+45}" y="240" text-anchor="middle">${s.label}</text>`;});return {title:'Movimentação de recomendações · '+year,html:svg+'</svg>'+`<p class="scope-note">${n(initial.value)} + ${n(add.value)} − ${n(subtract.value)} = ${n(closing.value)} recomendações. Concluídas podem ter sido emitidas em anos anteriores.</p>`};
 }
 const p=partition(group,byid,year);if(!p)return {title:'Composição · '+year,html:'<p class="empty">Composição não apresentada: exige categorias exclusivas, valores completos e soma conciliada com o total. Os valores qualificados permanecem nas outras visualizações.</p>'};
 const rows=p.rows.filter(r=>r.p.value>0).sort((a,b)=>b.p.value-a.p.value);let html=`<p class="chart-subtitle">Total conciliado: <b>${n(p.total.value)}</b> ${escape(rows[0]?.s.unit||'')}</p>`;
 if(rows.length<=6){const C=2*Math.PI*65;let offset=0;html+='<div class="donut-layout"><svg viewBox="0 0 190 190" role="img" aria-label="Participação das categorias no total"><title>Composição conciliada do total</title><circle cx="95" cy="95" r="65" fill="none" stroke="var(--surface-2)" stroke-width="28"/>';rows.forEach((r,i)=>{const arc=r.p.value/p.total.value*C;html+=`<circle cx="95" cy="95" r="65" fill="none" stroke="${palette[group.ids.indexOf(r.s.id)%palette.length]}" stroke-width="28" stroke-dasharray="${arc} ${C-arc}" stroke-dashoffset="${-offset}" transform="rotate(-90 95 95)"><title>${escape(label(r.s,p.rows))}: ${n(r.p.value)} · ${n(r.p.value/p.total.value*100)}%</title></circle>`;offset+=arc;});html+=`<text x="95" y="92" text-anchor="middle" class="donut-total">100%</text><text x="95" y="114" text-anchor="middle" class="chart-label">do total</text></svg><div>`;rows.forEach((r,i)=>{html+=`<button class="composition-row" data-indicator="${escape(r.s.id)}"><i style="background:${palette[group.ids.indexOf(r.s.id)%palette.length]}"></i><span>${escape(label(r.s,p.rows))}</span><strong>${n(r.p.value/p.total.value*100)}%</strong></button>`;});html+='</div></div>';
 }else{for(const r of rows.slice(0,10))html+=`<button class="share-row" data-indicator="${escape(r.s.id)}"><span>${escape(label(r.s,p.rows))}</span><strong>${n(r.p.value/p.total.value*100)}%</strong><span class="bar-track"><span class="bar-main" style="width:${r.p.value/p.total.value*100}%"></span></span></button>`;if(rows.length>10)html+=`<p class="scope-note">Demais ${rows.length-10} categorias: ${n(rows.slice(10).reduce((n,r)=>n+r.p.value,0)/p.total.value*100)}% do total.</p>`;}
 return {title:'Participação no total · '+year,html:html+'<p class="scope-note">Participação = categoria ÷ total conciliado × 100. Categorias com zero não recebem segmento.</p>'};
}
function sparkline(s,years,year){const ys=[...years].sort(),pts=ys.map(y=>get(s,y)),max=Math.max(1,...pts.map(p=>p?.value||0)),min=Math.min(0,...pts.map(p=>p?.value||0));const x=i=>8+i*224/Math.max(1,ys.length-1),y=v=>55-(v-min)/(max-min)*43;let svg=`<svg class="sparkline" viewBox="0 0 240 64" role="img" aria-label="Evolução de ${escape(s.title)}"><title>${ys.map((yr,i)=>yr+': '+(pts[i]?n(pts[i].value)+' '+s.unit:'não informado')).join('; ')}</title>`;for(let i=1;i<pts.length;i++)if(pts[i-1]&&pts[i])svg+=`<line x1="${x(i-1)}" y1="${y(pts[i-1].value)}" x2="${x(i)}" y2="${y(pts[i].value)}" class="spark-line"/>`;pts.forEach((p,i)=>{if(p)svg+=`<circle cx="${x(i)}" cy="${y(p.value)}" r="${ys[i]===String(year)?5:3}" fill="${ys[i]===String(year)?'var(--yellow)':'var(--navy)'}"/>`;});return svg+'</svg>';}
function history(s,years,year,baseline){const ys=[...years].sort(),pts=ys.map(y=>get(s,y)),W=700,H=280,L=75,R=36,T=35,B=45,max=Math.max(1,...pts.map(p=>p?.value||0))*1.18,x=i=>L+i*(W-L-R)/Math.max(1,ys.length-1),y=v=>H-B-(H-B-T)*v/max,compact=v=>Number(v).toLocaleString('pt-BR',{notation:'compact',maximumFractionDigits:1});let svg=`<svg class="history-chart" viewBox="0 0 ${W} ${H}" role="group" aria-label="Série histórica de ${escape(s.title)}, ${escape(s.scope)}, em ${escape(s.unit)}"><title>${escape(s.title)} · ${escape(s.unit)}</title>`;for(let j=0;j<=4;j++){const v=max*j/4;svg+=`<line x1="${L}" x2="${W-R}" y1="${y(v)}" y2="${y(v)}" class="chart-grid"/><text x="${L-12}" y="${y(v)+4}" text-anchor="end" class="chart-label">${compact(v)}</text>`;}for(let i=1;i<pts.length;i++)if(pts[i-1]&&pts[i])svg+=`<line x1="${x(i-1)}" y1="${y(pts[i-1].value)}" x2="${x(i)}" y2="${y(pts[i].value)}" class="history-line"/>`;pts.forEach((p,i)=>{svg+=`<text x="${x(i)}" y="${H-15}" text-anchor="middle" class="chart-label">${ys[i]}</text>`;if(!p){svg+=`<text x="${x(i)}" y="${H-B-12}" text-anchor="middle" class="chart-label">N/D</text>`;return;}const exact=Number(p.exact??p.value).toLocaleString('pt-BR',{maximumFractionDigits:10}),color=ys[i]===String(year)?'var(--yellow)':ys[i]===String(baseline)?'var(--chart-secondary)':'var(--navy)';svg+=`<g class="history-point" role="button" tabindex="0" data-indicator="${escape(s.id)}" data-history-year="${ys[i]}" aria-label="${ys[i]}: ${exact} ${escape(s.unit)}. Selecionar indicador e ano"><circle cx="${x(i)}" cy="${y(p.value)}" r="17" fill="transparent"/><circle cx="${x(i)}" cy="${y(p.value)}" r="${ys[i]===String(year)?7:5}" fill="${color}" stroke="var(--surface)" stroke-width="2"/><text x="${x(i)}" y="${y(p.value)-14}" text-anchor="middle" class="chart-label">${compact(p.value)}</text><title>${ys[i]}: ${exact} ${escape(s.unit)}</title></g>`;});return svg+'</svg>';}
function matrix(group,byid,years,year){let rows=group.ids.map(id=>({s:byid[id]})).filter(r=>r.s);if(new Set(rows.map(r=>r.s.unit)).size!==1)return '<p class="empty">Selecione um grupo com a mesma unidade para visualizar o mapa de calor.</p>';rows=rows.filter(r=>r.s.points.length).sort((a,b)=>(get(b.s,year)?.value??0)-(get(a.s,year)?.value??0));const total=rows.length;rows=rows.slice(0,12);const ys=[...years].sort(),max=Math.max(1,...rows.flatMap(r=>ys.map(y=>get(r.s,y)?.value||0)));let html='<div class="heatmap-scroll"><div class="heatmap-graphic" style="--years:'+ys.length+'"><span class="heatmap-axis">Categoria / ano</span>'+ys.map(y=>`<span class="heatmap-axis ${y===String(year)?'year-focus':''}">${escape(y)}</span>`).join('');for(const r of rows){html+=`<span class="heatmap-name" title="${escape(label(r.s,rows))}">${escape(label(r.s,rows).startsWith(group.title+' · ')?label(r.s,rows).slice(group.title.length+3):label(r.s,rows))}</span>`;for(const y of ys){const p=get(r.s,y);if(!p){html+='<span class="heatmap-tile missing-tile" aria-label="Sem valor qualificado">—</span>';continue;}const strength=8+p.value/max*82;html+=`<button class="heatmap-tile ${y===String(year)?'year-focus':''}" style="--strength:${strength}%;color:${strength>50?'var(--on-navy)':'var(--heading)'}" data-indicator="${escape(r.s.id)}" data-matrix-year="${escape(y)}" aria-label="${escape(label(r.s,rows))}, ${y}: ${n(p.value)} ${escape(r.s.unit)}" title="${n(p.value)} ${escape(r.s.unit)}">${n(p.value)}</button>`;}}return html+'</div></div><div class="heatmap-legend"><span>Menor valor</span><i></i><span>Maior valor</span></div>'+`<p class="scope-note">${total>12?'12 categorias com maiores valores no ano selecionado entre '+total+'. ':''}Unidade: ${escape(rows[0]?.s.unit||'')}. Intensidade proporcional ao maior valor do mapa. Traço: ausência de número qualificado. Clique em uma célula para explorar indicador e ano.</p>`;}
root.DashboardViews={label,partition,structure,matrix,sparkline,history};
})(globalThis);
