(()=>{
'use strict';
const el=id=>document.getElementById(id),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),M=globalThis.DashboardMath;
let data,byid,groups=[],comparisonRows=[],tableLimit=50,historyLimit=8,historyContext='';
const num=(v,d=2)=>v==null?'—':Number(v).toLocaleString('pt-BR',{maximumFractionDigits:d}),fmt=(p,s)=>p?.value==null?'Não informado':Number(p.exact).toLocaleString('pt-BR',{minimumFractionDigits:s.unit==='R$'?2:0,maximumFractionDigits:10});
const point=(s,y)=>s?.points.find(p=>p.year===String(y)),area=()=>data.areas.find(a=>a.id===el('dash-area').value),series=()=>byid[el('dash-indicator').value],year=()=>el('dash-year').value,baseline=()=>el('dash-baseline').value,scope=()=>el('dash-scope').value;
const entityKey=s=>s.scope+'|'+s.entity,center=s=>(s.entity||'').split(' · ')[0];
const eligible=()=>data.series.filter(s=>s.area===area().id&&point(s,year())&&(!scope()||s.scope===scope())&&(el('dash-detail').value==='all'||(el('dash-detail').value==='entity'?!!s.entity:!s.entity))&&(!el('dash-center').value||center(s)===el('dash-center').value)&&(!el('dash-entity').value||entityKey(s)===el('dash-entity').value));
function entityFilters(){const all=data.series.filter(s=>s.area===area().id&&s.entity&&point(s,year())&&(!scope()||s.scope===scope()));el('entity-filters').hidden=!data.series.some(s=>s.area===area().id&&s.entity);const old=el('dash-center').value;el('dash-center').innerHTML='<option value="">Todos os centros</option>'+[...new Set(all.map(center))].sort().map(c=>`<option value="${esc(c)}">${esc(c)}</option>`).join('');el('dash-center').value=all.some(s=>center(s)===old)?old:'';const oldEntity=el('dash-entity').value,list=all.filter(s=>!el('dash-center').value||center(s)===el('dash-center').value),unique=[...new Map(list.map(s=>[entityKey(s),s])).values()];el('dash-entity').innerHTML='<option value="">Todos os cursos / programas</option>'+unique.map(s=>`<option value="${esc(entityKey(s))}">${esc(s.entity)} · ${esc(s.scope)}</option>`).join('');el('dash-entity').value=unique.some(s=>entityKey(s)===oldEntity)?oldEntity:'';}

const sign=v=>v==null?'—':(v>0?'+':'')+num(v);
const variation=(p,b)=>{const c=M.change(p,b);return `${sign(c.percent)}${c.percent==null?'':'%'}`;};
function deltaText(s){const p=point(s,year()),b=point(s,baseline()),c=M.change(p,b);return c.difference==null?'Sem comparação disponível':`${sign(c.difference)} ${s.unit} · ${variation(p,b)} em relação a ${baseline()}`;}
function tabs(){el('subject-tabs').innerHTML=data.areas.map((a,i)=>`<button id="tab-${esc(a.id)}" class="subject-tab ${a.id===area().id?'active':''}" role="tab" aria-controls="dash-content" aria-selected="${a.id===area().id}" tabindex="${a.id===area().id?0:-1}" data-area="${esc(a.id)}"><span class="tab-number">${String(i+1).padStart(2,'0')}</span>${esc(a.title)}</button>`).join('');el('dash-content').setAttribute('aria-labelledby','tab-'+area().id);}
function scopes(){const old=scope(),opts=[...new Set(data.series.filter(s=>s.area===area().id).map(s=>s.scope))];el('dash-scope').innerHTML='<option value="">Todas as abrangências</option>'+opts.map(s=>`<option value="${esc(s)}">${esc(s)}</option>`).join('');el('dash-scope').value=opts.includes(old)?old:'';}
function selectArea(id){el('dash-area').value=id;el('dash-detail').value='';el('dash-center').value='';el('dash-entity').value='';scopes();el('history-search').value='';el('dash-table-search').value='';tableLimit=50;render();}
function groupOptions(){const a=area();groups=[...(a.groups||[])];if(a.comparison.length)groups.unshift({id:'padrao',title:'Comparação principal do assunto',ids:a.comparison});if(!groups.length)groups=[{id:'series',title:'Indicadores do assunto',ids:eligible().map(s=>s.id)}];const old=el('dash-group').value;el('dash-group').innerHTML=groups.map(g=>`<option value="${esc(g.id)}">${esc(g.title)}</option>`).join('');el('dash-group').value=groups.some(g=>g.id===old)?old:groups.find(g=>g.partition)?.id||groups[0].id;}
function activeGroup(){const g=groups.find(g=>g.id===el('dash-group').value)||groups[0];if(el('dash-detail').value!=='entity')return g;return {...g,ids:g.ids.filter(id=>{const s=byid[id];return s&&(!scope()||s.scope===scope())&&(!el('dash-center').value||center(s)===el('dash-center').value);})};}
function syncGroup(){const s=series();if(!s)return;const matches=groups.filter(g=>g.ids.includes(s.id)&&(!g.period||g.period===year())&&new Set(g.ids.map(id=>byid[id]?.unit)).size===1);const current=matches.find(g=>g.id===el('dash-group').value);if(!current&&matches.length)el('dash-group').value=matches.find(g=>s.entity?g.id.startsWith('cursos-')||g.id.startsWith('programas-'):g.partition)?.id||matches[0].id;}
function extraViews(){const g=activeGroup();const structure=DashboardViews.structure(g,byid,year());el('structure-title').textContent=structure.title;el('dash-structure').innerHTML=structure.html;el('matrix-title').textContent=g.title;el('dash-matrix').innerHTML=DashboardViews.matrix(g,byid,data.years,year());}
function drawTrend(s){el('trend-title').textContent=s.title;el('dash-trend').innerHTML=`<p class="chart-subtitle">${esc(s.scope)} · ${esc(s.unit)}</p>${DashboardViews.history(s,data.years,year(),baseline())}<div class="chart-legend"><span><i class="main-key"></i>Demais anos</span><span><i class="focus-key"></i>${year()} · referência</span><span><i class="baseline-key"></i>${baseline()} · comparação</span></div><p class="scope-note">Selecione um ponto para atualizar o ano. N/D: valor não informado ou período não identificado; lacunas não são interpoladas. ${esc(s.note)}</p>`;}
function historyRows(){const q=el('history-search').value.toLocaleLowerCase('pt-BR');return data.series.filter(s=>s.area===area().id&&(!scope()||s.scope===scope())&&(el('dash-detail').value==='all'||(el('dash-detail').value==='entity'?!!s.entity:!s.entity))&&(!el('dash-center').value||center(s)===el('dash-center').value)&&(!el('dash-entity').value||entityKey(s)===el('dash-entity').value)&&(s.title+' '+s.scope+' '+(s.entity||'')).toLocaleLowerCase('pt-BR').includes(q)).sort((a,b)=>Number(area().primary.includes(b.id))-Number(area().primary.includes(a.id)));}
function histories(){const context=[area().id,scope(),el('dash-detail').value,el('dash-center').value,el('dash-entity').value].join('|');if(context!==historyContext){historyLimit=8;historyContext=context;}const rows=historyRows();el('history-caption').textContent=`${Math.min(historyLimit,rows.length)} de ${rows.length} séries · ${scope()||'todas as abrangências'} · períodos qualificados entre 2020 e 2025`;el('history-more').hidden=rows.length<=historyLimit;el('history-grid').innerHTML=rows.slice(0,historyLimit).map(s=>`<article class="history-card"><button class="history-title" data-indicator="${esc(s.id)}">${esc(s.title)}</button><p class="chart-subtitle">${esc(s.scope)} · ${esc(s.unit)}${s.coverage?' · painel fixo de '+s.coverage.programs+' programas':''}</p>${DashboardViews.history(s,data.years,year(),baseline())}<details class="history-method"><summary>Definição do indicador</summary><p>${esc(s.note||s.points[0]?.method||'Valores anuais qualificados.')}</p></details></article>`).join('')||'<p class="empty">Nenhuma série histórica para este recorte.</p>';}
function comparison(g=activeGroup(), target="dash-comparison", titleTarget="dash-compare-title"){
 if(target==="dash-comparison")extraViews();let rows=g.ids.map(id=>byid[id]).filter(Boolean).map(s=>({s,p:point(s,year()),b:point(s,baseline())}));if(target==="dash-comparison")comparisonRows=rows;
 const units=new Set(rows.map(r=>r.s.unit));el(titleTarget).textContent=g.title;
 if(units.size>1){el(target).innerHTML='<div class="comparison-profiles">'+rows.filter(r=>r.p).slice(0,8).map(({s,p})=>`<button class="metric-profile" data-indicator="${esc(s.id)}"><span>${esc(DashboardViews.label(s,rows))}</span><strong>${esc(fmt(p,s))} <small>${esc(s.unit)}</small></strong>${DashboardViews.sparkline(s,data.years,year())}</button>`).join('')+'</div><p class="scope-note">Unidades distintas: cada tendência utiliza sua própria escala. Selecione um cartão para explorar a série.</p>';return;}
 const available=rows.filter(r=>r.p?.value!=null||r.b?.value!=null).sort((a,b)=>(b.p?.value??b.b.value)-(a.p?.value??a.b.value));const top=available.slice(0,10),selected=available.find(r=>r.s.id===el('dash-indicator').value);const included=selected&&!top.includes(selected);if(included)top.splice(9,1,selected);const max=Math.max(1,...top.flatMap(r=>[r.p?.value??0,r.b?.value??0]));
 const bar=(p,s,cls)=>p?.value==null?'<span class="missing-bar">N/D</span>':`<span class="bar-track"><span class="${cls}" style="width:${Math.max(0,p.value/max*100)}%"></span></span><strong>${esc(fmt(p,s))}</strong>`;
 el(target).innerHTML=top.length?`<div class="chart-legend"><span><i class="focus-key"></i>${esc(year())}</span><span><i class="main-key"></i>${esc(baseline())}</span></div>`+top.map(({s,p,b})=>`<button class="dash-bar ${s.id===el('dash-indicator').value?'is-selected':''}" data-indicator="${esc(s.id)}" aria-label="Detalhar ${esc(s.title)}, ${esc(s.scope)}"><span class="bar-label">${esc(DashboardViews.label(s,rows))}</span><span class="paired-bar"><span>${bar(p,s,'bar-focus')}</span><span>${bar(b,s,'bar-main')}</span></span><small>${esc(variation(p,b))}</small></button>`).join('')+`<p class="scope-note">${available.length>10?(included?'9 maiores valores e o indicador selecionado entre ':'10 maiores valores entre ')+available.length+' categorias. ':''}Unidade: ${esc(top[0].s.unit)}. Comparação entre categorias do mesmo grupo; os valores podem se sobrepor. ${rows.length-available.length?rows.length-available.length+' categorias sem valores nos dois anos.':''}</p>`:'<p class="empty">Não há valores para os anos selecionados.</p>';
}
function provenance(s){el('series-detail-title').textContent=s.title;el('dash-table-caption').textContent=`${s.scope}${s.entity?' · '+s.entity:''} · ${s.unit} · Apenas períodos qualificados`;el('dash-table').innerHTML=[...s.points].sort((a,b)=>b.year.localeCompare(a.year)).map(p=>`<tr class="${p.year===year()?'selected-year':''}"><td>${esc(p.year)}</td><td class="num"><strong>${esc(fmt(p,s))}</strong><span class="location">${esc(s.unit)}</span></td><td>${esc(p.method)}${s.note?`<p>${esc(s.note)}</p>`:''}</td></tr>`).join('');}
function derived(){const key=x=>typeof x==='number'?'indicador-'+x:x;let definitions=M.definitions.filter(d=>d.area===area().id&&(!scope()||scope()==='UFSCar')&&!el('dash-entity').value);if(el('dash-entity').value){const list=eligible(),find=t=>list.find(s=>s.title.startsWith(t));if(area().id==='graduacao'){const n=find('Ingressantes ·'),d=find('Vagas ·');if(n&&d)definitions=[{title:'Razão ingressantes / vagas do curso',num:n.id,den:d.id,unit:'%',factor:100,formula:'Ingressantes ÷ vagas × 100',note:'Razão descritiva; pode superar 100%. Não é taxa homologada de ocupação.'}];}else if(area().id==='pos'){for(const level of ['mestrado','doutorado']){const n=find('Defesas · '+level+' ·'),d=find('Matrículas · '+level+' ·');if(n&&d)definitions.push({title:'Defesas por 100 matrículas · '+level,num:n.id,den:d.id,unit:'%',factor:100,formula:'Defesas do ano ÷ matrículas do ano × 100',note:'Razão anual do programa; não é taxa de conclusão por coorte.'});}}}definitions=definitions.filter(d=>point(byid[key(d.num)],year())&&point(byid[key(d.den)],year())?.value>0);el('derived-section').hidden=!definitions.length;el('dash-derived').innerHTML=definitions.map(d=>{const n=byid[key(d.num)],s=byid[key(d.den)],np=point(n,year()),dp=point(s,year()),v=M.ratio(np,dp,d.factor),bv=M.ratio(point(n,baseline()),point(s,baseline()),d.factor);const max=Math.max(100,v||0,bv||0);return `<article class="derived-card"><span>${esc(d.title)}</span><strong>${num(v)} <small>${esc(d.unit)}</small></strong><div class="ratio-comparison"><div><span>${year()}</span><span class="bar-track"><span class="bar-focus" style="width:${v/max*100}%"></span></span><b>${num(v)} ${esc(d.unit)}</b></div>${bv!=null?`<div><span>${baseline()}</span><span class="bar-track"><span class="bar-main" style="width:${bv/max*100}%"></span></span><b>${num(bv)} ${esc(d.unit)}</b></div>`:''}</div>${d.unit==='%'&&v!=null&&bv!=null?`<p>${sign(v-bv)} pontos percentuais</p>`:''}<details><summary>Definição e cálculo</summary><p><b>${esc(d.formula)}</b></p><p>${esc(d.note)}</p><p>Numerador: ${esc(fmt(np,n))}; denominador: ${esc(fmt(dp,s))}.</p><button class="text-btn" data-indicator="${n.id}">Detalhar numerador</button><button class="text-btn" data-indicator="${s.id}">Detalhar denominador</button></details></article>`;}).join('');}
function areaRows(){const q=el('dash-table-search').value.toLocaleLowerCase('pt-BR');return eligible().filter(s=>(s.title+' '+s.scope+' '+s.entity).toLocaleLowerCase('pt-BR').includes(q));}
function areaTable(){const rows=areaRows();el('area-more').hidden=rows.length<=tableLimit;el('col-current').textContent=year();el('col-baseline').textContent=baseline();el('area-table-caption').textContent=`${rows.length} séries qualificadas · ${scope()||'todas as abrangências'} · clique em Detalhar para explorar a série`;
 el('dash-area-table').innerHTML=rows.length?rows.slice(0,tableLimit).map(s=>{const p=point(s,year()),b=point(s,baseline()),c=M.change(p,b);return `<tr><td><b>${esc(s.title)}</b><small>${esc(s.scope)}</small>${p?.missing?'<span class="coverage">Agregação com lacunas</span>':''}</td><td class="num">${esc(fmt(p,s))}</td><td class="num">${esc(fmt(b,s))}</td><td class="num">${sign(c.difference)}</td><td class="num">${esc(variation(p,b))}</td><td>${esc(s.unit)}</td><td><button class="text-btn" data-indicator="${esc(s.id)}">Detalhar</button></td></tr>`;}).join(''):'<tr><td colspan="7" class="empty">Nenhum indicador para estes filtros.</td></tr>';}
function updateIndicator(){const s=series();if(!s){el('dash-trend').innerHTML='<p class="empty">Sem série qualificada para o recorte.</p>';el('dash-table').innerHTML='';return;}drawTrend(s);provenance(s);syncGroup();comparison();el('dash-chips').innerHTML=`<span class="chip">${esc(area().title)}</span><span class="chip">${esc(year())} × ${esc(baseline())}</span><span class="chip">${esc(scope()||'Todas as abrangências')}</span><button class="chip" id="series-chip" title="Voltar ao indicador principal">${esc(s.title)} · ${esc(s.scope)} ×</button>`;el('series-chip').onclick=()=>{el('dash-indicator').value=eligible()[0]?.id;updateIndicator();};}

const personnelState={docentes:{metric:'indicador-1',group:'Docentes-Titulação'},tecnicos:{metric:'indicador-2',group:'TAs-Titulação'}};
const personnelConfig=[{key:'docentes',title:'Docentes',total:'indicador-1',prefix:'Docentes',offset:0},{key:'tecnicos',title:'Técnicos-Administrativos',total:'indicador-2',prefix:'Técnicos-Administrativos',offset:4}];
function personnelFigures(){
 const visible=area().id==='pessoas';el('personnel-figures').hidden=!visible;el('standard-main-figures').hidden=visible;el('standard-extra-figures').hidden=visible;if(!visible)return;
 el('personnel-figures').innerHTML=personnelConfig.map(c=>{
 const state=personnelState[c.key],list=eligible().filter(s=>s.title.startsWith(c.prefix));
 const availableGroups=area().groups.filter(g=>g.total===c.total&&(!scope()||g.ids.every(id=>byid[id]?.scope===scope())));
 if(!list.some(s=>s.id===state.metric))state.metric=list.find(s=>s.id===c.total)?.id||list[0]?.id;
 if(!availableGroups.some(g=>g.id===state.group))state.group=availableGroups[0]?.id;
 const selected=byid[state.metric],g=availableGroups.find(g=>g.id===state.group);
 const panel=(number,type,body)=>`<article class="dash-panel"><div class="figure-top"><span>FIGURA ${number} · ${type} · ${esc(c.title)}</span></div>${body}</article>`;
 const metricSelect=`<label class="personnel-select">Indicador de ${esc(c.title)}<select data-personnel-metric="${c.key}">${list.map(s=>`<option value="${s.id}" ${s.id===state.metric?'selected':''}>${esc(s.title)} · ${esc(s.scope)}</option>`).join('')}</select></label>`;
 const groupSelect=`<label class="personnel-select">Categorias de ${esc(c.title)}<select data-personnel-group="${c.key}">${availableGroups.map(x=>`<option value="${esc(x.id)}" ${x.id===state.group?'selected':''}>${esc(x.title)}</option>`).join('')}</select></label>`;
 const empty='<p class="empty">Não há dados qualificados desta categoria para a abrangência selecionada.</p>';
 return `<section class="personnel-section" data-personnel="${c.key}" aria-labelledby="${c.key}-heading"><h2 class="section-title" id="${c.key}-heading">${esc(c.title)}</h2><div class="dash-charts">`+
 panel(c.offset+1,'SÉRIE HISTÓRICA',metricSelect+(selected?`<h3>${esc(selected.title)}</h3><p class="chart-subtitle">${esc(selected.scope)} · ${esc(selected.unit)}</p>${DashboardViews.history(selected,data.years,year(),baseline())}<p class="scope-note">${esc(selected.note)} N/D: ausência de valor qualificado; lacunas não são interpoladas.</p>`:empty))+
 panel(c.offset+2,'COMPARAÇÃO',groupSelect+`<h3 id="${c.key}-compare-title"></h3><div id="${c.key}-comparison">${empty}</div>`)+
 panel(c.offset+3,'ESTRUTURA E FLUXOS',g?`<h3>${esc(g.title)} · ${year()}</h3>${DashboardViews.structure(g,byid,year()).html}`:empty)+
 panel(c.offset+4,'MAPA DE CALOR',g?`<h3>${esc(g.title)}</h3>${DashboardViews.matrix(g,byid,data.years,year())}`:empty)+`</div></section>`;
 }).join('');
 for(const c of personnelConfig){const g=area().groups.find(g=>g.id===personnelState[c.key].group);if(g)comparison(g,c.key+'-comparison',c.key+'-compare-title');}
}

function render(){
 entityFilters();const a=area(),previous=el('dash-indicator').value,list=eligible();tabs();groupOptions();el('dash-indicator').innerHTML=list.map(s=>`<option value="${esc(s.id)}">${esc(s.title)} · ${esc(s.scope)}</option>`).join('');el('dash-indicator').value=list.some(s=>s.id===previous)?previous:list.find(s=>a.primary.includes(s.id))?.id||list[0]?.id;
 let primary=a.primary.map(id=>byid[id]).filter(s=>point(s,year())&&(!scope()||s.scope===scope()));if(el('dash-entity').value)primary=list;else if(!primary.length)primary=list.filter(s=>!s.entity).slice(0,4);
 el('dash-content').innerHTML=`<div class="dash-area-heading"><h2 class="section-title">${esc(a.title)}</h2><p>${esc(a.description)}</p></div><div class="kpi-grid">${primary.map((s,i)=>{const p=point(s,year());return `<button class="kpi-card tone-${i%4}" data-indicator="${esc(s.id)}"><span>${esc(s.title)}</span><strong class="${p?.value==null?'no-value':''}">${esc(fmt(p,s))}</strong><small>${esc(s.unit)} · ${esc(s.scope)} · ${esc(year())}</small><div class="kpi-history">${DashboardViews.sparkline(s,data.years,year())}<span>${[...data.years].sort()[0]}–${[...data.years].sort().at(-1)}</span></div><em>${esc(deltaText(s))}</em>${s.coverage?`<span class="coverage">${s.coverage.programs} programas · painel fixo ${s.coverage.period}</span>`:''}</button>`;}).join('')}</div>`;
 el('qualification-note').textContent=`${list.length} séries com valor qualificado em ${year()} neste recorte. ${a.id==='pos'?'A síntese utiliza um painel fixo; selecione Cursos / programas para o detalhamento individual.':a.id==='graduacao'&&year()==='2025'?'Matrículas e concluintes de 2025 foram excluídos por ausência de cabeçalhos completos.':''}`;derived();comparison();areaTable();updateIndicator();histories();personnelFigures();globalThis.CampusMap?.render({visible:a.id==='infraestrutura',scope:scope(),year:year(),series:data.series,onSelect:name=>{el('dash-scope').value=name;render();}});el('area-more').hidden=areaRows().length<=tableLimit;
}
function chooseIndicator(id,scroll=false){const s=byid[id];if(!s)return;if(!point(s,year()))el('dash-year').value=[...s.points].sort((a,b)=>b.year.localeCompare(a.year))[0].year;el('dash-scope').value=s.scope;el('dash-detail').value=s.entity?'entity':'';el('dash-center').value=s.entity?center(s):'';entityFilters();el('dash-entity').value=s.entity?entityKey(s):'';render();el('dash-indicator').value=id;updateIndicator();if(area().id==='pessoas'){const c=personnelConfig.find(c=>s.title.startsWith(c.prefix));if(c)personnelState[c.key].metric=id;personnelFigures();}if(scroll)el(area().id==='pessoas'?'personnel-figures':'trend-title').scrollIntoView({behavior:'smooth',block:'start'});}
function csv(name,rows){const quote=v=>'"'+String(v??'').replace(/"/g,'""')+'"';const url=URL.createObjectURL(new Blob(['\ufeff'+rows.map(r=>r.map(quote).join(';')).join('\r\n')],{type:'text/csv;charset=utf-8'})),a=document.createElement('a');a.href=url;a.download=name+'.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),5000);}
function exportSeries(){const s=series();if(!s)return;csv(s.id+'_ufscar',[['Indicador','Abrangência','Ano','Valor exato','Unidade','Células ausentes/não numéricas','Cálculo'],...[...s.points].sort((a,b)=>b.year.localeCompare(a.year)).map(p=>[s.title,s.scope,p.year,p.exact,s.unit,p.missing,p.method])]);}
function comparativeCSV(list,name){csv(name,[['Indicador','Abrangência','Ano referência','Valor referência exato','Ano comparação','Valor comparação exato','Diferença calculada','Variação % calculada','Unidade','Células não numéricas referência'],...list.map(s=>{const p=point(s,year()),b=point(s,baseline()),c=M.change(p,b);return [s.title,s.scope,year(),p?.exact,baseline(),b?.exact,c.difference,c.percent,s.unit,p?.missing];})]);}
function toggleTheme(){const dark=document.documentElement.dataset.theme==='dark';document.documentElement.dataset.theme=dark?'light':'dark';el('theme-toggle').textContent=dark?'Tema escuro':'Tema claro';try{localStorage.setItem('ufscar-theme',dark?'light':'dark');}catch{}}
async function init(){try{
 const r=await fetch('dashboards.json');if(!r.ok)throw new Error('Não foi possível carregar os dashboards.');data=await r.json();M.configure(data);el('review-summary').textContent=`${data.review.qualifiedSeries} séries qualificadas · 2020–2025`;byid=Object.fromEntries(data.series.map(s=>[s.id,s]));el('dash-area').innerHTML=data.areas.map(a=>`<option value="${esc(a.id)}">${esc(a.title)}</option>`).join('');for(const id of ['dash-year','dash-baseline'])el(id).innerHTML=data.years.map(y=>`<option value="${esc(y)}">${esc(y)}</option>`).join('');el('dash-year').value='2025';el('dash-baseline').value='2024';el('dash-area').value='pessoas';
 el('dash-notes').innerHTML=data.notes.map(n=>`<h4>${esc(n.title)}</h4><p>${esc(n.text)}</p>`).join('')+'<h4>Comparabilidade</h4><p>As variações comparam os valores informados para o mesmo indicador e abrangência. Mudanças na cobertura, critérios ou cadastro da fonte podem afetar a comparação. Indicadores calculados são descritivos; metas e valores de referência não foram definidos.</p>';
 el('subject-tabs').onclick=e=>{const b=e.target.closest('[data-area]');if(b)selectArea(b.dataset.area);};el('subject-tabs').onkeydown=e=>{const b=e.target.closest('[data-area]');if(!b)return;const i=data.areas.findIndex(a=>a.id===b.dataset.area);let next;if(e.key==='ArrowRight')next=(i+1)%data.areas.length;if(e.key==='ArrowLeft')next=(i-1+data.areas.length)%data.areas.length;if(e.key==='Home')next=0;if(e.key==='End')next=data.areas.length-1;if(next!==undefined){e.preventDefault();selectArea(data.areas[next].id);el('tab-'+data.areas[next].id).focus();}};
 el('dash-area').onchange=()=>selectArea(el('dash-area').value);for(const id of ['dash-year','dash-baseline','dash-scope'])el(id).onchange=render;el('dash-indicator').onchange=()=>{updateIndicator();personnelFigures();};el('dash-group').onchange=()=>{const g=groups.find(g=>g.id===el('dash-group').value);if(g?.period&&year()!==g.period){el('dash-year').value=g.period;render();}else comparison();};el('dash-table-search').oninput=()=>{tableLimit=50;areaTable();el('area-more').hidden=areaRows().length<=tableLimit;};el('area-more').onclick=()=>{tableLimit+=50;areaTable();el('area-more').hidden=areaRows().length<=tableLimit;};for(const id of ['dash-detail','dash-center'])el(id).onchange=()=>{el('dash-entity').value='';if(id==='dash-center'&&el(id).value)el('dash-detail').value='entity';render();};el('dash-entity').onchange=()=>{if(el('dash-entity').value)el('dash-detail').value='entity';render();};el('dash-reset').onclick=()=>{el('dash-year').value='2025';el('dash-baseline').value='2024';el('dash-scope').value='';el('dash-detail').value='';el('dash-center').value='';el('dash-entity').value='';el('dash-table-search').value='';el('dash-indicator').value='';el('history-search').value='';historyLimit=8;render();};
 el('dash-export').onclick=exportSeries;el('trend-export').onclick=exportSeries;el('comparison-export').onclick=()=>comparativeCSV(comparisonRows.map(r=>r.s),area().id+'_comparacao');el('area-export').onclick=()=>comparativeCSV(areaRows(),area().id+'_indicadores');
 for(const id of ['dash-content','dash-comparison','dash-derived','dash-area-table','dash-structure'])el(id).onclick=e=>{const b=e.target.closest('[data-indicator]');if(b)chooseIndicator(b.dataset.indicator,id==='dash-area-table'||id==='dash-derived');};
 el('dash-matrix').onclick=e=>{const b=e.target.closest('[data-matrix-year]');if(b){el('dash-year').value=b.dataset.matrixYear;chooseIndicator(b.dataset.indicator);}};el('structure-export').onclick=()=>{const g=activeGroup();if(g.flow){const f=g.flow,rows=[['Saldo inicial',String(Number(year())-1),point(byid[f.stock],Number(year())-1)?.exact],['Emitidas',year(),point(byid[f.added],year())?.exact],['Concluídas',year(),point(byid[f.removed],year())?.exact],['Saldo final',year(),point(byid[f.stock],year())?.exact]];csv(area().id+'_movimentacao',[['Etapa','Ano','Valor','Unidade'],...rows.filter(r=>r[2]!=null).map(r=>[...r,'recomendações'])]);}else{const p=DashboardViews.partition(g,byid,year());csv(area().id+'_composicao',[['Categoria','Abrangência','Ano','Valor exato','Unidade','Participação % no total conciliado'],...g.ids.map(id=>({s:byid[id],p:point(byid[id],year())})).filter(r=>r.p).map(r=>[r.s.title,r.s.scope,year(),r.p.exact,r.s.unit,p?r.p.value/p.total.value*100:null])]);}};el('matrix-export').onclick=()=>{const g=activeGroup();csv(area().id+'_matriz',[['Categoria','Abrangência','Unidade',...data.years],...g.ids.map(id=>{const s=byid[id];return [s.title,s.scope,s.unit,...data.years.map(y=>point(s,y)?.exact)];})]);};
 const chooseHistory=e=>{const b=e.target.closest('[data-indicator]');if(!b)return;if(b.dataset.historyYear)el('dash-year').value=b.dataset.historyYear;chooseIndicator(b.dataset.indicator);};for(const id of ['dash-trend','history-grid']){el(id).onclick=chooseHistory;el(id).onkeydown=e=>{if((e.key==='Enter'||e.key===' ')&&e.target.closest('[data-history-year]')){e.preventDefault();chooseHistory(e);}};}el('history-search').oninput=()=>{historyLimit=8;histories();};el('history-more').onclick=()=>{historyLimit+=8;histories();};

 el('personnel-figures').onchange=e=>{const t=e.target;if(t.dataset.personnelMetric){personnelState[t.dataset.personnelMetric].metric=t.value;el('dash-indicator').value=t.value;updateIndicator();personnelFigures();}if(t.dataset.personnelGroup){personnelState[t.dataset.personnelGroup].group=t.value;personnelFigures();}};
 const personnelClick=e=>{const b=e.target.closest('[data-indicator]');if(!b)return;const container=b.closest('[data-personnel]');if(container)personnelState[container.dataset.personnel].metric=b.dataset.indicator;if(b.dataset.matrixYear||b.dataset.historyYear)el('dash-year').value=b.dataset.matrixYear||b.dataset.historyYear;chooseIndicator(b.dataset.indicator);};
 el('personnel-figures').onclick=personnelClick;el('personnel-figures').onkeydown=e=>{if((e.key==='Enter'||e.key===' ')&&e.target.closest('[data-history-year]')){e.preventDefault();personnelClick(e);}};
 el('theme-toggle').onclick=toggleTheme;el('print-dashboard').onclick=()=>window.print();try{document.documentElement.dataset.theme=localStorage.getItem('ufscar-theme')||'light';}catch{document.documentElement.dataset.theme='light';}el('theme-toggle').textContent=document.documentElement.dataset.theme==='dark'?'Tema claro':'Tema escuro';scopes();render();
 }catch(e){el('dash-error').hidden=false;el('dash-error').innerHTML=`${esc(e.message)} <button class="secondary" id="dash-retry">Tentar novamente</button>`;el('dash-retry').onclick=()=>location.reload();el('dash-content').textContent='Indicadores indisponíveis.';}}
init();
})();
